title = "case-study 2 parameters"

[debug]
species_name = ["Phyteuma betonicifolium"]
common_name = ["Betony-leaved Rampion"]
min_k = 2
max_k = 100000
max_stress = 0.25
trymax = 5
amount_target = 0.1
genetic_target = 0.85

[release]
species_name = ["Phyteuma betonicifolium"]
common_name = ["Betony-leaved Rampion"]
min_k = 2
max_k = 100000
max_stress = 0.25
trymax = 100
amount_target = 0.1
genetic_target = 0.95
