title = "case-study 2 parameters"

[debug]
species.name = ["Carex sempervirens"]
common.name = ["evergreen sedge"]
min.k = 2
max.k = 100000
max.stress = 0.25
trymax = 5
amount.target = 0.1
genetic.target = 0.8

[release]
species.name = ["Carex sempervirens"]
common.name = ["evergreen sedge"]
min.k = 2
max.k = 100000
max.stress = 0.25
trymax = 100
amount.target = 0.1
genetic.target = 0.8
