title = "case-study 2 parameters"

[debug]
species.name = ["Phyteuma betonicifolium"]
common.name = ["Betony-leaved Rampion"]
min.k = 2
max.k = 100000
max.stress = 0.25
trymax = 100
amount.target = 0.1
genetic.target = 0.85

[release]
species.name = ["Phyteuma betonicifolium"]
common.name = ["Betony-leaved Rampion"]
min.k = 2
max.k = 100000
max.stress = 0.25
trymax = 100
amount.target = 0.1
genetic.target = 0.95
