title = "simulation parameters"

[debug]
number_planning_units = 100
amount_target = 0.2
space_target = 0.90
blm = 2.5

[release]
number_planning_units = 100
amount_target = 0.2
space_target = 0.90
blm = 2.5
